"""Authoritative, scope-explicit Data Product persistence contract."""

from __future__ import annotations

from typing import Any, Protocol, Sequence

from packages.domain_model.data_product import (
    DataProduct,
    DataProductMembershipDecision,
    DataProductMembershipProposal,
    DataProductRevisionEvent,
    DataProductSLODefinition,
    DataProductSLOEvaluation,
)
from services.data_products.idempotency import DataProductIdempotencyRecord


class ProductVersionConflict(RuntimeError):
    pass


class DataProductRepository(Protocol):
    def reserve_idempotency(
        self, record_id: str, record: DataProductIdempotencyRecord
    ) -> DataProductIdempotencyRecord: ...
    def complete_idempotency(self, record_id: str, *, operation_id: str, revision: int, etag: str) -> None: ...

    # Every lookup takes trusted scope, even where the document also carries it.
    def create_product(self, product: DataProduct) -> DataProduct: ...
    def get_product(self, tenant_id: str, environment: str, product_id: str) -> DataProduct | None: ...
    def list_products(self, tenant_id: str, environment: str, **options: Any) -> Sequence[DataProduct]: ...
    def update_product(self, product: DataProduct, *, expected_etag: str) -> DataProduct: ...
    def activate_product(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> DataProduct: ...
    def deprecate_product(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> DataProduct: ...
    def archive_product(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> DataProduct: ...

    def begin_operation(self, event: DataProductRevisionEvent, product: DataProduct) -> DataProductRevisionEvent: ...
    def get_operation(self, tenant_id: str, environment: str, operation_id: str) -> DataProductRevisionEvent | None: ...
    def finish_operation(self, event: DataProductRevisionEvent) -> None: ...
    def list_pending_operations(self, tenant_id: str, environment: str, **options: Any) -> Sequence[Any]: ...
    def append_revision(self, product: DataProduct, *, actor: str, reason: str) -> None: ...
    def list_revisions(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def reconcile_pending_operations(self, tenant_id: str, environment: str, **options: Any) -> Sequence[Any]: ...

    def create_membership(self, tenant_id: str, environment: str, membership: Any, **options: Any) -> Any: ...
    def get_membership(self, tenant_id: str, environment: str, product_id: str, membership_id: str) -> Any: ...
    def list_memberships(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def exclude_membership(
        self, tenant_id: str, environment: str, product_id: str, membership_id: str, **options: Any
    ) -> Any: ...
    def create_membership_proposal(
        self, proposal: DataProductMembershipProposal, **options: Any
    ) -> DataProductMembershipProposal: ...
    def get_membership_proposal(
        self, tenant_id: str, environment: str, product_id: str, proposal_id: str
    ) -> DataProductMembershipProposal | None: ...
    def list_membership_proposals(
        self, tenant_id: str, environment: str, product_id: str, **options: Any
    ) -> Sequence[Any]: ...
    def accept_membership_proposal(
        self, tenant_id: str, environment: str, product_id: str, proposal_id: str, **options: Any
    ) -> Any: ...
    def reject_membership_proposal(
        self, tenant_id: str, environment: str, product_id: str, proposal_id: str, **options: Any
    ) -> Any: ...
    def expire_membership_proposal(
        self, tenant_id: str, environment: str, product_id: str, proposal_id: str, **options: Any
    ) -> Any: ...
    def supersede_membership_proposal(
        self, tenant_id: str, environment: str, product_id: str, proposal_id: str, **options: Any
    ) -> Any: ...
    def append_membership_decision(
        self, tenant_id: str, environment: str, product_id: str, decision: DataProductMembershipDecision, **options: Any
    ) -> Any: ...
    def list_membership_decisions(
        self, tenant_id: str, environment: str, product_id: str, **options: Any
    ) -> Sequence[Any]: ...

    def save_dependencies(
        self, tenant_id: str, environment: str, product_id: str, dependencies: Sequence[Any], **options: Any
    ) -> Any: ...
    def list_dependencies(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def get_direct_upstream(
        self, tenant_id: str, environment: str, product_id: str, **options: Any
    ) -> Sequence[Any]: ...
    def get_direct_downstream(
        self, tenant_id: str, environment: str, product_id: str, **options: Any
    ) -> Sequence[Any]: ...
    def get_transitive_upstream(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Any: ...
    def get_transitive_downstream(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Any: ...

    def create_slo(self, definition: DataProductSLODefinition) -> DataProductSLODefinition: ...
    def get_slo(
        self, tenant_id: str, environment: str, product_id: str, slo_id: str
    ) -> DataProductSLODefinition | None: ...
    def list_slos(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def update_slo(self, definition: DataProductSLODefinition, *, expected_etag: str) -> DataProductSLODefinition: ...
    def activate_slo(self, tenant_id: str, environment: str, product_id: str, slo_id: str, **options: Any) -> Any: ...
    def disable_slo(self, tenant_id: str, environment: str, product_id: str, slo_id: str, **options: Any) -> Any: ...
    def archive_slo(self, tenant_id: str, environment: str, product_id: str, slo_id: str, **options: Any) -> Any: ...
    def append_slo_revision(self, definition: DataProductSLODefinition, **options: Any) -> None: ...
    def list_slo_revisions(
        self, tenant_id: str, environment: str, product_id: str, slo_id: str, **options: Any
    ) -> Sequence[Any]: ...
    def save_slo_evaluation(self, evaluation: DataProductSLOEvaluation) -> DataProductSLOEvaluation: ...
    def get_slo_evaluation(
        self, tenant_id: str, environment: str, product_id: str, slo_id: str, evaluation_id: str
    ) -> DataProductSLOEvaluation | None: ...
    def list_slo_evaluations(
        self, tenant_id: str, environment: str, product_id: str, slo_id: str, **options: Any
    ) -> Sequence[Any]: ...

    def save_reliability_event(
        self, tenant_id: str, environment: str, product_id: str, event: Any, **options: Any
    ) -> Any: ...
    def save_current_reliability(
        self, tenant_id: str, environment: str, product_id: str, value: Any, **options: Any
    ) -> Any: ...
    def get_current_reliability(self, tenant_id: str, environment: str, product_id: str) -> Any: ...
    def list_reliability_history(
        self, tenant_id: str, environment: str, product_id: str, **options: Any
    ) -> Sequence[Any]: ...
    def save_coverage(self, tenant_id: str, environment: str, product_id: str, value: Any, **options: Any) -> Any: ...
    def get_coverage(self, tenant_id: str, environment: str, product_id: str) -> Any: ...
    def save_impact(self, tenant_id: str, environment: str, product_id: str, value: Any, **options: Any) -> Any: ...
    def get_impact(self, tenant_id: str, environment: str, product_id: str) -> Any: ...
    def list_incidents(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def list_changes(self, tenant_id: str, environment: str, product_id: str, **options: Any) -> Sequence[Any]: ...
    def readiness(self) -> dict[str, Any]: ...
