#!/usr/bin/env python3
"""Render/check volatile active readiness facts from canonical machine sources."""

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from scripts.release.current_terminal_migration import migration_report

ROOT = Path(__file__).resolve().parents[2]


def render():
    chart = yaml.safe_load((ROOT / "helm/dataobs/Chart.yaml").read_text())
    candidate = yaml.safe_load((ROOT / "docs/release/first-supported-platform-candidate.yaml").read_text())
    matrix = yaml.safe_load((ROOT / "docs/release/supported-platform-matrix.yaml").read_text())
    supported = matrix.get("supported", [])
    return f"""# Current production readiness\n\n<!-- Generated by scripts/release/render_current_production_readiness.py; do not edit facts manually. -->\n* **Active candidate source:** `{candidate.get("candidate_source_sha") or "unknown"}`\n* **Terminal migration:** `{migration_report()["terminal_migration"]}`\n* **Application / chart:** `{chart["appVersion"]}` / `{chart["version"]}`\n* **Release decision:** **NO_GO**\n* **Supported platforms:** {"none (`supported: []`)" if not supported else supported}\n\nThis bounded active view is evidence-derived. Historical audit documents are not rewritten. Implemented or locally tested does not mean hosted tested, certified, supported, or releasable.\n"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    path = ROOT / "docs/release/current-production-readiness.md"
    value = render()
    if a.check:
        if path.read_text() != value:
            raise SystemExit("active production readiness is stale; run renderer")
        print("active production readiness: synchronized")
    else:
        path.write_text(value)


if __name__ == "__main__":
    main()
