#!/usr/bin/env python3
import argparse
import hashlib
from pathlib import Path

import yaml

INPUTS = [
    "docs/security/security-controls.yaml",
    "docs/security/security-evidence-registry.yaml",
    "docs/security/security-findings.yaml",
    "docs/security/security-exceptions.yaml",
]


def digest():
    h = hashlib.sha256()
    for p in INPUTS:
        h.update(Path(p).read_bytes())
    return h.hexdigest()


def render():
    controls = yaml.safe_load(Path(INPUTS[0]).read_text())["controls"]
    evidence = yaml.safe_load(Path(INPUTS[1]).read_text())["evidence"]
    findings = yaml.safe_load(Path(INPUTS[2]).read_text())["findings"]
    exceptions = yaml.safe_load(Path(INPUTS[3]).read_text())["exceptions"]
    states = {
        s: sum(c["implementation_state"] == s for c in controls)
        for s in ("implemented", "local_tested", "hosted_tested", "independently_verified")
    }
    missing = sum(e["status"] in ("missing", "stale", "failed", "partial", "unvalidated") for e in evidence)
    blocking = sum(f["state"] in ("open", "accepted") and f["severity"] == "critical" for f in findings)
    return f"""# Current security posture\n\n<!-- Generated by scripts/security/render_current_security_posture.py; source-digest: {digest()} -->\n\n**Overall posture: INCOMPLETE. Security release gate: INCOMPLETE. Current product release decision: NO_GO.**\n\n| Measure | Count |\n|---|---:|\n| Controls | {len(controls)} |\n| Implemented | {states["implemented"]} |\n| Locally tested | {states["local_tested"]} |\n| Hosted tested | {states["hosted_tested"]} |\n| Independently verified | {states["independently_verified"]} |\n| Missing/stale/failed/partial/unvalidated evidence entries | {missing} |\n| Blocking findings | {blocking} |\n| Active exceptions | {len(exceptions)} |\n\nImplemented does not mean verified. Local tests do not mean hosted tests. Missing evidence never passes. Current-release hosted tenant, OIDC/TLS, backup/DR and exact-SHA vulnerability/SBOM/provenance/signature evidence remain absent or unvalidated. No numeric security score or external certification is asserted.\n"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    p.add_argument("--output", type=Path, default=Path("docs/security/current-security-posture.md"))
    a = p.parse_args()
    expected = render()
    if a.check:
        return 0 if a.output.exists() and a.output.read_text() == expected else 1
    a.output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
