apiVersion: v1
kind: Service
metadata:
  name: dataobs-api
  namespace: dataobs
spec:
  selector:
    app: dataobs-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
