import type { CommandCenter, Topology } from "../api/types";
export const commandFixture: CommandCenter = {
  overall_health: "critical",
  critical_incidents: 3,
  affected_services: 7,
  data_status: {
    complete: false,
    warnings: ["AI and cost telemetry are not configured"],
    sources: ["assets", "incidents", "kafka", "pathways"],
    observed_at: "2026-07-18T12:42:18Z",
  },
  pillars: [
    {
      id: "platform",
      name: "Platform observability",
      health: "warning",
      metric: "94.2% collection",
      issues: 2,
      coverage: "Complete",
      trend: "↑ 1.8%",
    },
    {
      id: "pipelines",
      name: "Pipeline & job observability",
      health: "critical",
      metric: "4 failed runs",
      issues: 4,
      coverage: "Complete",
      trend: "↑ 2",
    },
    {
      id: "data",
      name: "Data observability",
      health: "critical",
      metric: "12 quality failures",
      issues: 12,
      coverage: "Complete",
      trend: "↓ 5%",
    },
    {
      id: "finops",
      name: "FinOps / cost observability",
      health: "unknown",
      metric: "Not configured",
      issues: 0,
      coverage: "Not configured",
    },
    {
      id: "business",
      name: "Business observability",
      health: "warning",
      metric: "7 services affected",
      issues: 7,
      coverage: "Partial coverage",
    },
    {
      id: "ai",
      name: "AI / agent observability",
      health: "unknown",
      metric: "No recent data",
      issues: 0,
      coverage: "No recent data",
    },
  ],
  priority_items: [
    {
      id: "inc-1042",
      problem: "Checkout events retention window at risk",
      entity: "orders.events.v2",
      owner: "Streaming Platform",
      service: "Order fulfillment",
      started: "38m ago",
      severity: "Critical",
      impact: "14 downstream assets",
      automation: "Awaiting approval",
    },
    {
      id: "inc-1038",
      problem: "Freshness SLO breached",
      entity: "warehouse.orders_daily",
      owner: "Data Products",
      service: "Revenue reporting",
      started: "1h 12m",
      severity: "High",
      impact: "6 dashboards",
      automation: "Investigating",
    },
    {
      id: "inc-1031",
      problem: "Schema compatibility changed",
      entity: "payments.authorized",
      owner: "Payments",
      service: "Checkout",
      started: "2h 08m",
      severity: "High",
      impact: "3 consumers",
      automation: "Case opened",
    },
  ],
  recent_changes: [
    {
      id: "1",
      title: "Schema evolved · payments.authorized",
      detail: "Field payment_method became required",
      time: "12m ago",
    },
    {
      id: "2",
      title: "Workflow verified · scanner recovery",
      detail: "Collection completeness restored to 94.2%",
      time: "31m ago",
    },
  ],
};
export const topologyFixture: Topology = {
  truncated: false,
  data_status: {
    complete: true,
    warnings: [],
    sources: ["pathway-worker", "kafka-observer"],
    observed_at: "2026-07-18T12:42:18Z",
  },
  nodes: [
    {
      id: "pg",
      name: "orders-db",
      type: "source",
      health: "healthy",
      owner: "Order Platform",
      badges: ["fresh"],
    },
    {
      id: "producer",
      name: "checkout-api",
      type: "service",
      health: "healthy",
      owner: "Checkout",
    },
    {
      id: "topic",
      name: "orders.events.v2",
      type: "topic",
      health: "critical",
      owner: "Streaming Platform",
      business_service: "Order fulfillment",
      badges: ["lag", "retention risk"],
    },
    {
      id: "transform",
      name: "enrich-orders",
      type: "job",
      health: "warning",
      owner: "Data Products",
    },
    {
      id: "dataset",
      name: "warehouse.orders_daily",
      type: "dataset",
      health: "critical",
      owner: "Data Products",
      badges: ["freshness", "quality"],
    },
    {
      id: "dash",
      name: "Revenue pulse",
      type: "dashboard",
      health: "warning",
      owner: "Finance Analytics",
    },
  ],
  edges: [
    {
      id: "e1",
      source_node_id: "pg",
      destination_node_id: "producer",
      health: "healthy",
      confidence: 1,
      throughput: 600,
    },
    {
      id: "e2",
      source_node_id: "producer",
      destination_node_id: "topic",
      health: "critical",
      confidence: 1,
      throughput: 1800,
    },
    {
      id: "e3",
      source_node_id: "topic",
      destination_node_id: "transform",
      health: "warning",
      confidence: 1,
      throughput: 1250,
    },
    {
      id: "e4",
      source_node_id: "transform",
      destination_node_id: "dataset",
      health: "critical",
      confidence: 0.92,
      throughput: 420,
    },
    {
      id: "e5",
      source_node_id: "dataset",
      destination_node_id: "dash",
      health: "warning",
      confidence: 0.55,
      throughput: 80,
    },
  ],
};
