apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataobs.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "dataobs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  dataobs.yaml: |
{{ .Values.config.dataobsYaml | indent 4 }}
  otel-collector-config.yaml: |
{{ .Values.config.otelCollectorYaml | indent 4 }}
