{{- range $name, $cfg := dict "api" .Values.api "console" .Values.console "quality-worker" .Values.qualityWorker "scanner-worker" .Values.scannerWorker "monitor-runtime" .Values.monitorRuntime "pathway-worker" .Values.pathwayWorker "kafka-observer" .Values.kafkaObserver "otel-collector" .Values.otelCollector }}
{{- if and $cfg.enabled $cfg.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataobs.fullname" $ }}-{{ $name }}
  labels: {{- include "dataobs.labels" $ | nindent 4 }}
automountServiceAccountToken: {{ $cfg.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
