from typing import Protocol

from .models import *


class DataObsConnector(Protocol):
    def capabilities(self) -> ConnectorCapabilities: ...
    def test_connection(self) -> ConnectionTestResult: ...
    def discover(self, request: DiscoveryRequest) -> DiscoveryResult: ...
    def schema_snapshot(self, request: SchemaScanRequest) -> SchemaSnapshot: ...
    def freshness(self, request: FreshnessRequest) -> FreshnessResult: ...
    def profile(self, request: ProfileRequest) -> ProfileResult: ...
    def quality(self, request: QualityRequest) -> QualityResult: ...
    def lineage(self, request: LineageRequest) -> LineageResult: ...
    def query_history(self, request: QueryHistoryRequest) -> QueryHistoryResult: ...
    def checkpoint(self) -> ConnectorCheckpoint: ...
    def close(self) -> None: ...
