from enum import StrEnum


class Permission(StrEnum):
    AUTH_READ = "auth:read"
    PLATFORM_ADMIN = "platform:admin"
    TENANT_ADMIN = "tenant:admin"
    IAM_READ = "iam:read"
    IAM_WRITE = "iam:write"
    AUDIT_READ = "audit:read"
    ASSETS_READ = "assets:read"
    ASSETS_WRITE = "assets:write"
    LINEAGE_READ = "lineage:read"
    LINEAGE_WRITE = "lineage:write"
    QUALITY_READ = "quality:read"
    QUALITY_WRITE = "quality:write"
    QUALITY_EXECUTE = "quality:execute"
    MONITORS_READ = "monitors:read"
    MONITORS_WRITE = "monitors:write"
    MONITORS_EXECUTE = "monitors:execute"
    DATA_PRODUCTS_READ = "data_products:read"
    DATA_PRODUCTS_WRITE = "data_products:write"
    JOBS_READ = "jobs:read"
    JOBS_EXECUTE = "jobs:execute"
    STREAMS_READ = "streams:read"
    STREAMS_EXECUTE = "streams:execute"
    INCIDENTS_READ = "incidents:read"
    INCIDENTS_WRITE = "incidents:write"
    WORKFLOWS_READ = "workflows:read"
    WORKFLOWS_EXECUTE = "workflows:execute"
    WORKFLOWS_APPROVE = "workflows:approve"
    INTEGRATIONS_READ = "integrations:read"
    INTEGRATIONS_WRITE = "integrations:write"
    COLLECTION_INGEST = "collection:ingest"
    COLLECTION_MANAGE = "collection:manage"
