"""Auditable, method-aware and anchored API permission policy."""

from .permissions import Permission

PUBLIC_ROUTES = frozenset({("GET", "/livez"), ("GET", "/readyz"), ("GET", "/health"), ("GET", "/api/v1/auth/config")})
ROUTE_PERMISSIONS: dict[tuple[str, str], Permission] = {
    ("GET", "/api/v1/auth/config"): Permission.PLATFORM_ADMIN,
    ("GET", "/api/v1/auth/me"): Permission.AUTH_READ,
    ("GET", "/api/v1/iam/role-bindings"): Permission.IAM_READ,
    ("POST", "/api/v1/iam/role-bindings"): Permission.IAM_WRITE,
    ("PATCH", "/api/v1/iam/role-bindings/{binding_id}"): Permission.IAM_WRITE,
    ("GET", "/api/v1/iam/role-bindings/{binding_id}"): Permission.IAM_READ,
    ("DELETE", "/api/v1/iam/role-bindings/{binding_id}"): Permission.IAM_WRITE,
    ("GET", "/livez"): Permission.PLATFORM_ADMIN,
    ("GET", "/readyz"): Permission.PLATFORM_ADMIN,
    ("GET", "/health"): Permission.PLATFORM_ADMIN,
    ("POST", "/api/v1/findings"): Permission.INCIDENTS_WRITE,
    ("GET", "/api/v1/findings"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/findings/{finding_id}"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/incidents"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/incidents/{incident_id}"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/incidents/{incident_id}/events"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/incidents/{incident_id}/evidence"): Permission.INCIDENTS_READ,
    ("GET", "/api/v1/incidents/{incident_id}/impact"): Permission.INCIDENTS_READ,
    ("POST", "/api/v1/incidents/{incident_id}/acknowledge"): Permission.INCIDENTS_WRITE,
    ("POST", "/api/v1/incidents/{incident_id}/assign"): Permission.INCIDENTS_WRITE,
    ("POST", "/api/v1/incidents/{incident_id}/suppress"): Permission.INCIDENTS_WRITE,
    ("POST", "/api/v1/incidents/{incident_id}/resolve"): Permission.INCIDENTS_WRITE,
    ("POST", "/api/v1/incidents/{incident_id}/reopen"): Permission.INCIDENTS_WRITE,
    ("POST", "/api/v1/incidents/{incident_id}/run-workflow"): Permission.WORKFLOWS_EXECUTE,
    ("POST", "/api/v1/incidents/{incident_id}/actions/preview"): Permission.WORKFLOWS_EXECUTE,
    ("POST", "/api/v1/incidents/{incident_id}/actions/execute"): Permission.WORKFLOWS_EXECUTE,
    ("GET", "/api/v1/incidents/{incident_id}/actions"): Permission.INCIDENTS_READ,
    ("POST", "/api/v1/approvals/{approval_id}/approve"): Permission.WORKFLOWS_APPROVE,
    ("POST", "/api/v1/approvals/{approval_id}/reject"): Permission.WORKFLOWS_APPROVE,
    ("GET", "/rules"): Permission.QUALITY_READ,
    ("GET", "/quality/results"): Permission.QUALITY_READ,
    ("GET", "/quality/results/{result_id}"): Permission.QUALITY_READ,
    ("GET", "/lineage/nodes"): Permission.LINEAGE_READ,
    ("GET", "/lineage/edges"): Permission.LINEAGE_READ,
    ("POST", "/rules"): Permission.QUALITY_WRITE,
    ("DELETE", "/rules/{rule_id}"): Permission.QUALITY_WRITE,
    ("GET", "/lineage/impact/{node_id:path}"): Permission.LINEAGE_READ,
    ("POST", "/quality/results"): Permission.QUALITY_WRITE,
    ("POST", "/api/data-observability/assets"): Permission.ASSETS_WRITE,
    ("GET", "/api/data-observability/assets"): Permission.ASSETS_READ,
    ("GET", "/api/data-observability/assets/{asset_id:path}/lineage"): Permission.ASSETS_READ,
    ("GET", "/api/v1/kafka/clusters"): Permission.STREAMS_READ,
    ("GET", "/api/v1/kafka/clusters/{cluster_id}"): Permission.STREAMS_READ,
    ("GET", "/api/data-observability/assets/{asset_id:path}/health"): Permission.ASSETS_READ,
    ("GET", "/api/data-observability/assets/{asset_id:path}"): Permission.ASSETS_READ,
    ("POST", "/api/data-observability/assets/{asset_id:path}/columns"): Permission.ASSETS_WRITE,
    ("POST", "/api/data-observability/quality-checks"): Permission.QUALITY_WRITE,
    ("POST", "/api/data-observability/quality-runs"): Permission.QUALITY_WRITE,
    ("GET", "/api/data-observability/quality-runs"): Permission.QUALITY_READ,
    ("POST", "/api/data-observability/job-runs"): Permission.JOBS_EXECUTE,
    ("GET", "/api/data-observability/job-runs"): Permission.JOBS_READ,
    ("POST", "/api/v1/openlineage/events"): Permission.COLLECTION_INGEST,
    ("POST", "/api/v1/lineage"): Permission.COLLECTION_INGEST,
    ("POST", "/api/data-observability/lineage/events"): Permission.COLLECTION_INGEST,
    ("GET", "/api/v1/runs/{run_id}"): Permission.JOBS_READ,
    ("GET", "/api/v1/jobs/{namespace}/{name:path}"): Permission.JOBS_READ,
    ("GET", "/api/v1/datasets/{namespace}/{name:path}"): Permission.PLATFORM_ADMIN,
    ("GET", "/api/v1/lineage/{asset_id}/upstream"): Permission.ASSETS_READ,
    ("GET", "/api/v1/lineage/{asset_id}/downstream"): Permission.ASSETS_READ,
    ("GET", "/api/v1/lineage/{asset_id}/impact"): Permission.ASSETS_READ,
    ("GET", "/api/v1/lineage/{asset_id}/columns/{column}/upstream"): Permission.ASSETS_READ,
    ("GET", "/api/v1/pillars"): Permission.ASSETS_READ,
    ("GET", "/api/v1/migrations"): Permission.PLATFORM_ADMIN,
    ("POST", "/api/v1/tenants"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/tenants"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/sources"): Permission.INTEGRATIONS_WRITE,
    ("GET", "/api/v1/sources"): Permission.INTEGRATIONS_READ,
    ("POST", "/api/v1/integrations"): Permission.INTEGRATIONS_WRITE,
    ("GET", "/api/v1/integrations"): Permission.INTEGRATIONS_READ,
    ("POST", "/api/v1/collectors"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/collectors"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/collectors/{collector_id}/heartbeat"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/scanners"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/heartbeat"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/scanners/{scanner_id}/tasks"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/tasks/{task_id}/claim"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/tasks/{task_id}/renew"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/tasks/{task_id}/fail"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/tasks/{task_id}/ack"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scanners/{scanner_id}/tasks/{task_id}/results"): Permission.COLLECTION_MANAGE,
    ("POST", "/api/v1/scan-policies"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/scan-policies"): Permission.COLLECTION_MANAGE,
    ("GET", "/api/v1/assets"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/schema"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/schema/changes"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/freshness"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/profile"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/quality"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/lineage"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/impact"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}"): Permission.ASSETS_READ,
    ("GET", "/api/v1/command-center"): Permission.ASSETS_READ,
    ("GET", "/api/v1/topology"): Permission.ASSETS_READ,
    ("GET", "/api/v1/assets/{asset_id}/{section}"): Permission.ASSETS_READ,
    ("POST", "/api/v1/pathway-explorer/search"): Permission.LINEAGE_WRITE,
    ("GET", "/api/v1/entities/{node_id}/summary"): Permission.PLATFORM_ADMIN,
    ("GET", "/api/v1/topology/nodes/{node_id}"): Permission.ASSETS_READ,
    ("GET", "/api/v1/events/stream"): Permission.STREAMS_READ,
    ("GET", "/strategy/enterprise-backlog"): Permission.PLATFORM_ADMIN,
}
for key in PUBLIC_ROUTES:
    ROUTE_PERMISSIONS.pop(key, None)


def permission_for(method: str, route_template: str) -> Permission:
    try:
        return ROUTE_PERMISSIONS[(method.upper(), route_template)]
    except KeyError as exc:
        raise LookupError(f"route has no permission policy: {method.upper()} {route_template}") from exc
