"""Durable repository contracts for the monitor runtime.

Production implementations must persist every transition and always scope reads by
tenant and environment.  The protocol deliberately makes that scope impossible to
omit from history and lease operations.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Protocol, Sequence

from packages.domain_model.monitor import MonitorDefinition, MonitorEvaluation, MonitorFinding, MonitorObservation


class VersionConflict(RuntimeError):
    """The supplied optimistic-concurrency token is stale."""


class ConsistencyError(RuntimeError):
    """An immutable event conflicts with already persisted history."""


class MonitorRepository(Protocol):
    def create_monitor(self, monitor: MonitorDefinition) -> MonitorDefinition: ...
    def get_monitor(self, tenant_id: str, environment: str, monitor_id: str) -> MonitorDefinition | None: ...
    def list_monitors(
        self, tenant_id: str, environment: str, *, limit: int, cursor: str | None = None
    ) -> Sequence[MonitorDefinition]: ...
    def update_monitor(self, monitor: MonitorDefinition, *, expected_etag: str) -> MonitorDefinition: ...
    def archive_monitor(
        self, tenant_id: str, environment: str, monitor_id: str, *, expected_etag: str
    ) -> MonitorDefinition: ...
    def append_definition_event(self, monitor: MonitorDefinition, *, actor: str, action: str) -> None: ...
    def list_definition_history(
        self, tenant_id: str, environment: str, monitor_id: str, *, limit: int
    ) -> Sequence[dict[str, Any]]: ...
    def list_due_schedules(
        self, tenant_id: str, environment: str, before: datetime, limit: int
    ) -> Sequence[dict[str, Any]]: ...
    def save_schedule_state(self, tenant_id: str, environment: str, monitor_id: str, state: dict[str, Any]) -> None: ...
    def acquire_lease(
        self, tenant_id: str, environment: str, lease_id: str, owner: str, now: datetime, expires_at: datetime
    ) -> bool: ...
    def renew_lease(
        self, tenant_id: str, environment: str, lease_id: str, owner: str, expires_at: datetime
    ) -> bool: ...
    def release_lease(self, tenant_id: str, environment: str, lease_id: str, owner: str) -> bool: ...
    def history(
        self, tenant_id: str, environment: str, monitor_id: str, before: datetime, limit: int
    ) -> Sequence[MonitorObservation]: ...
    def append_observation(self, observation: MonitorObservation) -> bool: ...
    def create_baseline_version(self, baseline: dict[str, Any]) -> bool: ...
    def get_current_baseline(self, tenant_id: str, environment: str, monitor_id: str) -> dict[str, Any] | None: ...
    def list_baseline_versions(
        self, tenant_id: str, environment: str, monitor_id: str, *, limit: int
    ) -> Sequence[dict[str, Any]]: ...
    def reset_baseline(
        self, tenant_id: str, environment: str, monitor_id: str, *, actor: str, reason: str
    ) -> dict[str, Any]: ...
    def save_evaluation(self, evaluation: MonitorEvaluation, *, idempotency_key: str) -> bool: ...
    def get_evaluation(self, tenant_id: str, environment: str, evaluation_id: str) -> MonitorEvaluation | None: ...
    def list_evaluations(
        self, tenant_id: str, environment: str, monitor_id: str, *, limit: int
    ) -> Sequence[MonitorEvaluation]: ...
    def save_finding(self, finding: MonitorFinding, *, idempotency_key: str) -> bool: ...
    def bulk_observations(self, observations: Iterable[MonitorObservation]) -> int: ...
    def create_suppression(self, suppression: dict[str, Any]) -> dict[str, Any]: ...
    def get_active_suppressions(
        self, tenant_id: str, environment: str, monitor_id: str, at: datetime
    ) -> Sequence[dict[str, Any]]: ...
    def end_suppression(
        self, tenant_id: str, environment: str, suppression_id: str, *, actor: str
    ) -> dict[str, Any]: ...
    def create_recommendation(self, recommendation: dict[str, Any]) -> dict[str, Any]: ...
    def get_recommendation(self, tenant_id: str, environment: str, recommendation_id: str) -> dict[str, Any] | None: ...
    def list_recommendations(self, tenant_id: str, environment: str, *, limit: int) -> Sequence[dict[str, Any]]: ...
    def transition_recommendation(
        self, tenant_id: str, environment: str, recommendation_id: str, state: str, *, actor: str
    ) -> dict[str, Any]: ...
    def save_coverage(self, tenant_id: str, environment: str, coverage: dict[str, Any]) -> None: ...
    def get_coverage(self, tenant_id: str, environment: str) -> dict[str, Any] | None: ...
    def get_checkpoint(self, tenant_id: str, environment: str, monitor_id: str) -> dict[str, Any] | None: ...
    def checkpoint(
        self, tenant_id: str, environment: str, monitor_id: str, value: dict[str, Any], *, expected_revision: int | None
    ) -> int: ...
